name: Update Open Source Contributions

on:
  push:
    paths:
      - 'config.json'

  schedule:
    - cron: "2 10 * * 0"  # Every Sunday at 3:32 PM IST (10:02 AM UTC)

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python generate.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md

          git diff --staged --quiet || (git commit -m "Auto update contributions" && git push)
